[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; 配置依赖库
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.0
    olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0

; 针对大体积固件的优化（如果后续需要使用更多 Flash 空间）
board_build.partitions = huge_app.csv
